// Penrose Whirlpool Mirage
// A mesmerizing animation of Penrose tiling swirling like a vortex, casting warm gold and orange hues, creating a mirage-like effect using quasicrystal patterns.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum

float penroseRhomb(vec2 p) {
    vec2 x = mod(p, 1.0);
    float d1 = length(x - vec2(0.5));
    float d2 = length(x - vec2(0.5 + 0.5 * sin(iTime * 0.3), 0.5 * cos(iTime * 0.4)));
    return min(d1, d2);
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;
    float t = iTime * 0.5;
    mat2 rot = rotate2d(t);
    uv *= rot;

    float f = 1.0;
    float col = 0.0;
    for (int i = 0; i < 6; i++) {
        uv *= 3.5;
        uv += hash(floor(uv) + floor(iTime)) - 0.5;
        f *= 1.4;
        col += penroseRhomb(uv * 0.8) / f;
    }

    vec3 color = hsv2rgb(vec3(col * 0.7 + 0.3, 0.9, 1.0));
    fragColor = vec4(color, 1.0);
}
