// Aurora Penrose Mirage
// An animated Penrose tiling shader with oceanic colors, simulating a mirage effect over deep blue waters with hints of teal and white foam.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum

float penroseTile(vec2 p) {    float s = sin(iTime * 0.5);    vec2 q = vec2(s, cos(iTime * 0.5)) * 1.9;    mat2 m1 = rotate2d(72.0 * 3.14159 / 180.0), m2 = rotate2d(144.0 * 3.14159 / 180.0);    float d1 = length(mod(p, q) - q * 0.5);    float d2 = min(d1, length(mod(m1 * p, q) - q * 0.5));    float d3 = min(d2, length(mod(m2 * p, q) - q * 0.5));    return d3;}void mainImage(out vec4 fragColor, in vec2 fragCoord) {    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;    float a = penroseTile(uv * 3.0);    vec3 col = mix(vec3(0.0, 0.1, 0.4), vec3(0.0, 0.8, 0.9), smoothstep(0.2, 0.3, a));    col += smoothstep(0.05, 0.0, length(uv) - 0.7) * vec3(1.0, 1.0, 1.0);    fragColor = vec4(col, 1.0);}
