// Psychedelic Fractal Flow
// A dynamic psychedelic pattern created using polar transformations, sine functions, and noise. The animation creates flowing color patterns with fractal-like structures.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum
// Shadertoy-compatible: paste into Shadertoy and hit play!

float noise(vec2 st) {
    return fract(sin(dot(st.xy, vec2(12.9898,78.233))) * 43758.5453123);
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 pos = (fragCoord * 2.0 - iResolution.xy) / min(iResolution.x, iResolution.y);
    
    // Time-based animation
    float t = iTime * 0.5;
    
    // Polar coordinates
    vec2 uv = pos;
    float angle = atan(uv.y, uv.x) + t;
    float dist = length(uv);
    
    // Create complex transformations
    uv = vec2(
        sin(dist * 10.0 + t) * cos(angle),
        cos(dist * 15.0 - t) * sin(angle)
    );
    
    // Add noise for organic feel
    float n = noise(vec2(t, t));
    vec3 color = vec3(
        abs(sin(uv.x * 8.0 + t)) * cos(n),
        abs(cos(uv.y * 6.0 - t)) * sin(n),
        abs(sin(angle * 4.0 + t)) * cos(2.0*n)
    );
    
    // Mix with distance to create depth
    float mixVal = smoothstep(0.5, 1.5, dist);
    color = mix(vec3(0.0), color, mixVal);
    
    fragColor = vec4(pow(color, vec3(1.0)), 1.0);
}
