// Ethereal Nebula Whispers
// A pastel dreamscape featuring domain warping with fbm to create an ethereal, flowing nebula effect that subtly animates over time.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum

float turbulence(vec2 p) { float sum = 0.0; float freq = 1.0; float amp = 1.0; for (int i = 0; i < 8; i++) { sum += fbm(p * freq) * amp; freq *= 2.0; amp *= 0.5; } return sum; }
void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;
    float timeFactor = iTime * 0.1;
    uv *= rotate2d(timeFactor);
    uv += turbulence(uv + vec2(iTime, -iTime)) * 0.3;
    float nebulaDensity = fbm(uv * 4.0 + timeFactor) * 0.5 + 0.5;
    vec3 color = mix(vec3(1.0, 0.8, 0.9), vec3(0.6, 0.9, 1.0), nebulaDensity);
    color *= smoothstep(0.2, 1.0, length(uv) * 2.0);
    fragColor = vec4(color, 1.0);
}
