// Neon Hyperbolic Lattice
// A cyberpunk aesthetic rendering of a neon hyperbolic lattice using non-Euclidean tiling, animated to create an electric and dynamic visual effect.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum

float sdHyperboloid(vec3 p) { return length(p.xz) - exp(sin(iTime + p.y)); }
void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = (fragCoord * 2.0 - iResolution) / iResolution.y;
    vec3 ro = vec3(0.0, sin(iTime * 0.5), 1.0);
    vec3 rd = normalize(vec3(uv, -1.0));
    float t = 0.0;
    float d;
    for (int i = 0; i < 80; i++) {
        vec3 p = ro + rd * t;
        d = sdHyperboloid(p);
        if (d < 0.001) break;
        t += d;
        if (t > 20.0) break;
    }
    vec3 col = vec3(0.0);
    if (t < 20.0) {
        vec3 p = ro + rd * t;
        float v = fbm(p.xz * 5.0 + iTime * 0.1) * 0.5 + 0.5;
        vec3 neonColor = hsv2rgb(vec3(v, 1.0, 1.0)) * 2.0;
        col = mix(col, neonColor, smoothstep(0.0, 0.1, abs(d)));
    }
    fragColor = vec4(pow(col, vec3(0.8)), 1.0);
}
