// Psychedelic Fractal Flow
// A visually dynamic shader that creates a flowing fractal pattern with psychedelic colors, using iterative function systems and domain warping.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum

float domainWarp(vec2 p) {
    return fbm(p * 3.0 + iTime) - fbm(p * 4.5 - iTime);
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;
    float scale = sin(iTime * 0.3) * 0.5 + 1.5;
    uv *= scale;

    // Apply domain warping
    uv.x += domainWarp(uv);
    uv.y += domainWarp(uv.yx);

    vec2 z = uv;
    float iter = 0.0;
    for (float i = 0.0; i < 16.0; i++) {
        z = abs(z) / dot(z, z) - sin(iTime * 0.5);
        iter += exp(-length(z));
    }

    // Convert to HSV and back for color effect
    vec3 colHSV = vec3(iter * 0.1 + iTime * 0.1, 1.0, 1.0);
    vec3 colRGB = hsv2rgb(colHSV);

    fragColor = vec4(colRGB, 1.0);
}
