// AquaWave Distortion
// An animated oceanic wave pattern using domain warping with fbm to create a dynamic, flowing effect with deep blues and teal hues.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum

float wave(vec2 p) { return sin(p.x * 10.0 + iTime * 3.0) * cos(p.y * 10.0 + iTime * 3.0); }
void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;
    float fbmVal = fbm(uv * 2.0);
    uv += wave(uv) * 0.1 + fbmVal * 0.3;
    float c = sin(uv.x * 40.0 + fbmVal * 50.0 + iTime * 10.0) * 0.5 + 0.5;
    vec3 col = mix(vec3(0.2, 0.4, 0.6), vec3(0.8, 1.0, 1.0), c);
    fragColor = vec4(col, 1.0);
}
