// Ethereal Truchet Kaleidoscope
// A monochromatic Truchet tiling pattern that animates over time, creating a flowing kaleidoscopic effect. The shader uses noise functions to introduce subtle variations and a sense of movement.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum

float truchetTile(vec2 p) {
    vec2 id = floor(p);
    float hashVal = hash(id.x + id.y * 57.0);
    float patternIndex = fract(hashVal * 4.0);
    vec2 ip = fract(p);
    if (patternIndex < 1.0) return step(ip.x, ip.y);
    if (patternIndex < 2.0) return step(1.0 - ip.x, ip.y);
    if (patternIndex < 3.0) return step(ip.x, 1.0 - ip.y);
    return step(1.0 - ip.x, 1.0 - ip.y);
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / min(iResolution.x, iResolution.y);
    uv *= 8.0 + sin(iTime * 0.5) * 2.0;
    float tilePattern = truchetTile(uv);
    vec3 color = mix(vec3(0.1), vec3(0.9), tilePattern);
    fragColor = vec4(color, 1.0);
}
