// Cosmic Fractal Swirl
// A psychedelic color field created using layered sine waves with time-based transformations, creating a hypnotic swirling effect.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum
// Shadertoy-compatible: paste into Shadertoy and hit play!

vec3 hsv2rgb(vec3 c) {
    vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);
    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord.xy / iResolution.xy;
    uv = 2.0 * uv - 1.0;
    float time = iTime * 0.5;
    
    // Create a rotating coordinate system
    float angle = time + atan(uv.y, uv.x);
    vec2 st = vec2(
        sin(angle) * length(uv),
        cos(angle) * length(uv)
    );
    
    // Generate multiple frequency layers
    float pattern = 0.0;
    for(float i = 1.0; i < 6.0; i++) {
        pattern += sin(pow(2.0, i) * st.x + time) * 
                   cos(pow(3.0, i) * st.y - time);
    }
    pattern /= 5.0;
    
    // Convert to HSV and back for vibrant colors
    vec3 hsv = vec3(
        fract(time / 2.0 + pattern),
        abs(sin(time)) * 0.7 + 0.3,
        smoothstep(0.0, 1.0, abs(pattern) * 4.0)
    );
    
    vec3 rgb = hsv2rgb(hsv);
    fragColor = vec4(rgb, 1.0);
}
