// Fractal Mirror Maze
// A kaleidoscopic reflection effect using recursive fractals, creating a mesmerizing mirror maze with high contrast and a touch of red accent.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum

float snoise(vec2 v) { return noise(v); }

vec2 kaleidoscope(vec2 p, float n) {
    float angle = atan(p.y, p.x);
    float radius = length(p);
    angle = mod(angle * n, 3.14159265 / n);
    return vec2(cos(angle), sin(angle)) * radius;
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = (fragCoord - iResolution.xy / 2.0) / min(iResolution.x, iResolution.y);
    uv *= 10.0;
    float time = iTime * 0.5;

    vec3 col = vec3(0.0);
    for (int i = 0; i < 6; i++) {
        vec2 kuv = kaleidoscope(uv, pow(2.0, float(i))) + time;
        float n = snoise(kuv) * 0.5 + 0.5;
        col += vec3(n > 0.8 ? 1.0 : 0.0, n < 0.2 ? 1.0 : 0.0, n > 0.9 ? 1.0 : 0.0) * pow(0.6, float(i));
    }

    fragColor = vec4(col, 1.0);
}
