// Gilded Refractive Nexus
// This shader creates a kaleidoscopic effect with gilded colors, simulating refractive layers that twist and swirl, giving the impression of a complex, ethereal refractive prism.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum

float hash_float(float n) { return fract(sin(n)*43758.5453); }
vec2 hash_vec2(vec2 p) { return vec2(hash_float(p.x), hash_float(p.y)); }
float noise_float(float x) { float i = floor(x); float f = fract(x); float u = f * f * (3.0 - 2.0 * f); return mix(hash_float(i), hash_float(i + 1.0), u); }
mat2 rotate2d_mat2(float angle) { return mat2(cos(angle), -sin(angle), sin(angle), cos(angle)); }
void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = (fragCoord - iResolution.xy * 0.5) / iResolution.x;
    float time = iTime * 0.1;
    for (int i = 0; i < 6; i++) {
        uv *= rotate2d_mat2(noise_float(time + float(i)));
        uv = fract(uv) - 0.5;
        uv /= dot(uv, uv) + 0.5;
    }
    vec3 color = hsv2rgb(vec3(hash_vec2(floor(uv * 100.0)).x, 0.8, 0.9));
    color *= smoothstep(0.4, 0.6, length(uv) / sqrt(2.0));
    fragColor = vec4(color * 1.5, 1.0);
}
