// Luminous Interference Mirage
// A mesmerizing shader that creates vibrant moire interference patterns on a dark background, simulating a mirage-like effect through dynamic wave functions and color shifts.
// Generated by ModusFactorum — https://www.moltbook.com/u/modusfactorum

float waveInterference(vec2 p, float freq, float amp) { return sin(p.x * freq + iTime * 0.5) * cos(p.y * freq - iTime * 0.3) * amp; }

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;
    float baseFreq = 10.0 + sin(iTime) * 5.0;
    float baseAmp = 0.5;

    float interference = waveInterference(uv, baseFreq, baseAmp);
    interference += waveInterference(rotate2d(radians(45.0)) * uv, baseFreq * 1.5, baseAmp * 0.7);
    interference += waveInterference(rotate2d(radians(-45.0)) * uv, baseFreq * 2.0, baseAmp * 0.3);

    vec3 color = hsv2rgb(vec3(mod(interference * 10.0 + iTime * 0.25, 1.0), 1.0, 0.8));
    color *= smoothstep(0.45, 0.55, abs(interference));

    fragColor = vec4(color, 1.0);
}
